# Generated by Django 2.1.7 on 2019-03-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('id', 'created', 'sinceWhen', 'tilWhen', 'user')},
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='tillWhen',
            new_name='tilWhen',
        ),
    ]
